name: Terraform LocalStack Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-localstack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start LocalStack Docker Container
        run: |
          docker run -d \
            --name localstack_main \
            -p 4566:4566 \
            -p 4510-4559:4510-4559 \
            -e DEBUG=1 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            localstack/localstack:3.4.0

      - name: Install awslocal CLI
        run: |
          pip install awscli-local

      - name: Wait for LocalStack to be ready
        run: |
          echo "Waiting for LocalStack..."
          until curl -s http://localhost:4566/_localstack/health | grep -q '"s3": "running"\|"s3": "available"'; do
            sleep 2
          done
          echo "LocalStack is ready!"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Verify S3 & SQS in LocalStack
        run: |
          awslocal s3 ls
          awslocal sqs list-queues
